### ISSUE TITLE
Roadmap to V1

### ISSUE THREAD

**Issue by kwelch** [kwelch/babel-plugin-captains-log#10]
The main reason I wrote this was for the inject variable names feature. The inject scope was the first feature, but is hacky at best.

To move toward a true release candidate, 

- [x] Scope Injection default: false
- [x] Move Scope injection to experimental
- [x] Update docs for usage
- [x] Provide better examples

These are changes based on current implementation. Please reply with any additional features or settings you would like to see added.

**Comment by kwelch** [comment]
For v1 I also want to put together a blog post of lessons learned, inspirations, and next steps.

**Comment by kwelch** [comment]
Released :tada:
